spring:
  datasource:
    url: jdbc:postgresql://postgres-container-financialservice:5432/financialservicedb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
